export const CHANGE_FILTER_HOTEL_NAME = "CHANGE_FILTER_HOTEL_NAME";
export const CHANGE_PRICE_FILTER_LIMITS = "CHANGE_PRICE_FILTER_LIMITS";
export const CHANGE_PRICE_FILTER_VALUES = "CHANGE_PRICE_FILTER_VALUES";
