export const CHANGE_START_DATE = "CHANGE_START_DATE";
export const CHANGE_END_DATE = "CHANGE_END_DATE";
export const SEARCH_LOADING_START = "SEARCH_LOADING_START";
export const SEARCH_LOADING_END = "SEARCH_LOADING_END";
export const SEARCH_FIRE_ERROR = "SEARCH_FIRE_ERROR";
