export const CHANGE_START_DATE = "CHANGE_START_DATE";
export const CHANGE_END_DATE = "CHANGE_END_DATE";
export const SEARCH_START_LOADING = "SEARCH_START_LOADING";
export const SEARCH_END_LOADING = "SEARCH_END_LOADING";
export const SEARCH_FAILED = "SEARCH_FAILED";
export const STORE_SEARCH_RESULT = "STORE_SEARCH_RESULT";
